name: Release

on:
  workflow_dispatch

jobs:
  build-core:
    name: Build core
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Echo
        run: echo "Building core"


  build-plugins:
    needs: build-core
    strategy:
        matrix:
          repo: ['ManiVaultStudio/BinIO', 'ManiVaultStudio/MeanShiftClustering']
    runs-on: windows-latest
    steps:
      - name: Echo
        run: echo Building ${{ matrix.repo }}

  build-installer:
    needs: build-plugins
    runs-on: windows-latest
    steps:
      - name: Echo
        run: echo Building installer
        
#name: Build core

#on:
#  workflow_dispatch
    
#jobs:
##  build-core:
    #name: Build core
    #runs-on: windows-latest
    #steps:
     # - name: Trigger workflow in core
     #   uses: peter-evans/repository-dispatch@v1
     #   with:
     #     token: ${{ secrets.PA_TOKEN }}
     ##     repository: ManiVaultStudio/core
      #    event-type: core-completed
      #    client-payload: |-
      #      {
      #        "repo": {
      #          "name": "ManiVaultStudio/core",
      #          "branch": "release/1.0"
      #        }
      #      }
