name: Release

on:
  workflow_dispatch:
    inputs:
      ref:
        description: 'Branch to trigger the workflow on'
        required: true
        default: 'release/core_1.0/0.5'

jobs:
  build-core:
    name: Build core
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Echo
        run: echo "Building core"
  build-plugins:
    needs: build-core
    strategy:
        matrix:
          inputs:
            - '{ "repo": "BinIO", "branch": "release/core_1.0/0.5" }'
            - '{ "repo": "CsvLoader", "branch": "release/core_1.0/0.5" }'
    runs-on: ubuntu-latest
    steps:
      - name: Install jq
        run: sudo apt-get install -y jq
      - name: Parse JSON
        id: parse_json
        run: |
          input='${{ matrix.inputs }}'
          repo=$(echo $input | jq -r '.repo')
          branch=$(echo $input | jq -r '.branch')
          echo "repo=$repo" >> $GITHUB_ENV
          echo "branch=$branch" >> $GITHUB_ENV
      - name: Trigger plugin build workflow
        id: trigger_workflow
        shell: bash
        run: |
          TOKEN="${{ secrets.PA_TOKEN }}"
          REPO=ManiVaultStudio/"echo $repo"
          REF="echo $branch"
          
          RESPONSE=$(curl -s -X POST -H "Authorization: token $TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/$REPO/actions/workflows/build.yml/dispatches \
            -d "{\"ref\":\"$REF\"}")

          echo "Triggered workflow for building the core: $RESPONSE"
          
      - name: Wait for plugin build workflow to complete
        id: wait_workflow
        shell: bash
        run: |
          TOKEN="${{ secrets.PA_TOKEN }}"
          REPO="echo $repo"
          RUN_ID=""
          STATUS=""

          while [ "$STATUS" != "completed" ]; do
            RUN_ID=$(curl -s -H "Authorization: token $TOKEN" \
              "https://api.github.com/repos/$REPO/actions/runs?branch=${{ github.event.inputs.ref }}" \
              | jq -r '.workflow_runs | map(select(.status == "in_progress")) | .[0].id')

            if [ -n "$RUN_ID" ]; then
              STATUS=$(curl -s -H "Authorization: token $TOKEN" \
                "https://api.github.com/repos/$REPO/actions/runs/$RUN_ID" \
                | jq -r '.status')
              echo "Current status: $STATUS"

              if [ "$STATUS" == "completed" ]; then
                CONCLUSION=$(curl -s -H "Authorization: token $TOKEN" \
                  "https://api.github.com/repos/$REPO/actions/runs/$RUN_ID" \
                  | jq -r '.conclusion')
                echo "Workflow completed with conclusion: $CONCLUSION"
                if [ "$CONCLUSION" != "success" ]; then
                  exit 1
                fi
                break
              fi
            else
              echo "Workflow has not started yet. Waiting..."
            fi
            sleep 10
          done

  build-installer:
    needs: build-plugins
    runs-on: windows-latest
    steps:
      - name: Echo
        run: echo Building installer
        
#name: Build core

#on:
#  workflow_dispatch
    
#jobs:
##  build-core:
    #name: Build core
    #runs-on: windows-latest
    #steps:
     # - name: Trigger workflow in core
     #   uses: peter-evans/repository-dispatch@v1
     #   with:
     #     token: ${{ secrets.PA_TOKEN }}
     ##     repository: ManiVaultStudio/core
      #    event-type: core-completed
      #    client-payload: |-
      #      {
      #        "repo": {
      #          "name": "ManiVaultStudio/core",
      #          "branch": "release/1.0"
      #        }
      #      }
