name: Releaser

on:
  workflow_dispatch:
    inputs:
      ref:
        description: 'Branch to trigger the workflow on'
        required: true
        default: 'all'
        type: string
        
jobs:
  build-core:
    name: Build core
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Echo
        run: echo "Building core"
  build-plugins:
    runs-on: ubuntu-latest
    needs: build-core
    strategy:
        matrix:
          inputs:
            - { "repo": "BinIO", "branch": "release/core_1.0/0.5" }
            - { "repo": "CsvLoader", "branch": "release/core_1.0/0.5" }
    name: Build - ${{ matrix.inputs.repo }}
    steps:
      - name: Trigger plugin build workflow
        uses: the-actions-org/workflow-dispatch@v4
        with:
          workflow: build.yml
          repo: ManiVaultStudio/${{ matrix.inputs.repo }}
          ref: ${{ matrix.inputs.branch }}
          token: ${{ secrets.PA_TOKEN }}
          wait-for-completion: true
          wait-for-completion-timeout: 2h
          display-workflow-run-url: true
          workflow-logs: print
  build-installer:
    needs: build-plugins
    runs-on: ubuntu-latest
    steps:
      - name: Echo
        run: echo Building installer

#name: Build core

#on:
#  workflow_dispatch
    
#jobs:
##  build-core:
    #name: Build core
    #runs-on: windows-latest
    #steps:
     # - name: Trigger workflow in core
     #   uses: peter-evans/repository-dispatch@v1
     #   with:
     #     token: ${{ secrets.PA_TOKEN }}
     ##     repository: ManiVaultStudio/core
      #    event-type: core-completed
      #    client-payload: |-
      #      {
      #        "repo": {
      #          "name": "ManiVaultStudio/core",
      #          "branch": "release/1.0"
      #        }
      #      }
