name: Release

on:
  workflow_dispatch:
    inputs:
      ref:
        description: 'Branch to trigger the workflow on'
        required: true
        default: 'release/core_1.0/0.5'

jobs:
  build-core:
    name: Build core
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Echo
        run: echo "Building core"


  build-plugins:
    needs: build-core
    strategy:
        matrix:
          repo: ['ManiVaultStudio/BinIO']
    runs-on: windows-latest
    steps:
      - name: Trigger plugin build workflow
        id: trigger_workflow
        shell: bash
        run: |
          TOKEN="${{ secrets.PA_TOKEN }}"
          REPO="${{ matrix.repo }}"
          REF="${{ github.event.inputs.ref }}"
          
          RESPONSE=$(curl -s -X POST -H "Authorization: token $TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/$REPO/actions/workflows/build.yml/dispatches \
            -d "{\"ref\":\"$REF\"}")

          echo "Triggered workflow for building the core: $RESPONSE"
          
      - name: Wait for plugin build workflow to complete
        id: wait_workflow
        shell: bash
        run: |
          TOKEN="${{ secrets.PA_TOKEN }}"
          REPO="${{ matrix.repo }}"
          RUN_ID=""
          STATUS=""

          while [ -z "$RUN_ID" ]; do
            RUN_ID=$(curl -s -H "Authorization: token $TOKEN" \
              "https://api.github.com/repos/$REPO/actions/runs?branch=${{ github.event.inputs.ref }}" \
              | jq -r '.workflow_runs | map(select(.status == "in_progress")) | .[0].id')
            sleep 5
          done

          echo "Run ID: $RUN_ID"
          
          while [ "$STATUS" != "completed" ]; do
            STATUS=$(curl -s -H "Authorization: token $TOKEN" \
              "https://api.github.com/repos/$REPO/actions/runs/$RUN_ID" \
              | jq -r '.status')
            echo "Current status: $STATUS"
            if [ "$STATUS" == "completed" ]; then
              CONCLUSION=$(curl -s -H "Authorization: token $TOKEN" \
                "https://api.github.com/repos/$REPO/actions/runs/$RUN_ID" \
                | jq -r '.conclusion')
              echo "Workflow completed with conclusion: $CONCLUSION"
              if [ "$CONCLUSION" != "success" ]; then
                exit 1
              fi
              break
            fi
            sleep 5
          done

  build-installer:
    needs: build-plugins
    runs-on: windows-latest
    steps:
      - name: Echo
        run: echo Building installer
        
#name: Build core

#on:
#  workflow_dispatch
    
#jobs:
##  build-core:
    #name: Build core
    #runs-on: windows-latest
    #steps:
     # - name: Trigger workflow in core
     #   uses: peter-evans/repository-dispatch@v1
     #   with:
     #     token: ${{ secrets.PA_TOKEN }}
     ##     repository: ManiVaultStudio/core
      #    event-type: core-completed
      #    client-payload: |-
      #      {
      #        "repo": {
      #          "name": "ManiVaultStudio/core",
      #          "branch": "release/1.0"
      #        }
      #      }
