name: Releaser

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Application name'
        required: true
        default: '1.0'
        type: choice
        options:
        - '1.0'
        - GeneSurfer
jobs:
  build-core:
    name: Build core
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Echo
        run: echo "Building core"
  configure:
    runs-on: ubuntu-latest
    needs: build-core
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
     - name: Checkout to repository
       uses: actions/checkout@v3
     - name: Set matrix data
       id: set-matrix
       run: echo "matrix=$(jq -c . < ./config.json | jq -r 'tostring')" >> $GITHUB_OUTPUT
  build-plugins:
    runs-on: ubuntu-latest
    needs: configure
    strategy:
        matrix: ${{ fromJson(needs.configure.outputs.matrix) }}
    name: Build - ${{ matrix.repo }}
    steps:
      - name: Show matrix
        run: echo ${{ matrix }}
      - name: Trigger plugin build workflow
        uses: the-actions-org/workflow-dispatch@v4
        with:
          workflow: build.yml
          repo: ManiVaultStudio/${{ matrix.repo }}
          ref: ${{ matrix.branch }}
          token: ${{ secrets.PA_TOKEN }}
          wait-for-completion: true
          wait-for-completion-timeout: 2h
          display-workflow-run-url: true
          workflow-logs: print
  build-installer:
    needs: build-plugins
    runs-on: ubuntu-latest
    steps:
      - name: Echo
        run: echo Building installer

#name: Build core

#on:
#  workflow_dispatch
    
#jobs:
##  build-core:
    #name: Build core
    #runs-on: windows-latest
    #steps:
     # - name: Trigger workflow in core
     #   uses: peter-evans/repository-dispatch@v1
     #   with:
     #     token: ${{ secrets.PA_TOKEN }}
     ##     repository: ManiVaultStudio/core
      #    event-type: core-completed
      #    client-payload: |-
      #      {
      #        "repo": {
      #          "name": "ManiVaultStudio/core",
      #          "branch": "release/1.0"
      #        }
      #      }
