name: Releaser

on:
  workflow_dispatch:
    inputs:
      ref:
        description: 'Branch to trigger the workflow on'
        required: true
        default: 'all'
        type: string
        
jobs:
  build-core:
    name: Build core
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Echo
        run: echo "Building core"
  build-plugins:
    runs-on: ubuntu-latest
    needs: build-core
    steps:
      - name: Trigger external workflow
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build.yml
          owner: ManiVaultStudio
          repo: BinIO
          ref: release/core_1.0/0.5
          token: ${{ secrets.PA_TOKEN }}
          wait-for-completion: true
  build-installer:
    needs: build-plugins
    runs-on: ubuntu-latest
    steps:
      - name: Echo
        run: echo Building installer

#name: Build core

#on:
#  workflow_dispatch
    
#jobs:
##  build-core:
    #name: Build core
    #runs-on: windows-latest
    #steps:
     # - name: Trigger workflow in core
     #   uses: peter-evans/repository-dispatch@v1
     #   with:
     #     token: ${{ secrets.PA_TOKEN }}
     ##     repository: ManiVaultStudio/core
      #    event-type: core-completed
      #    client-payload: |-
      #      {
      #        "repo": {
      #          "name": "ManiVaultStudio/core",
      #          "branch": "release/1.0"
      #        }
      #      }
