name: Releaser

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Application name'
        required: true
        default: '1.0'
        type: choice
        options:
        - '1.0'
        - GeneSurfer
      skip-core:
        type: boolean
        description: Skip core build
      build-installer:
        type: boolean
        description: Build installer
        default: true
jobs:
  build-core:
    name: Build core
    runs-on: ubuntu-latest
    steps:
      - name: Trigger core build workflow
        uses: the-actions-org/workflow-dispatch@v4
        if: ${{ inputs.skip-core == 'false' }}
        with:
          workflow: build.yml
          repo: ManiVaultStudio/core
          ref: release/${{ inputs.version }}
          token: ${{ secrets.PA_TOKEN }}
          wait-for-completion: true
          wait-for-completion-timeout: 2h
          display-workflow-run-url: true
          workflow-logs: print
  load-config:
    name: Load configuration
    runs-on: ubuntu-latest
    needs: build-core
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Get JSON content
        id: get-json-content
        run: |
          echo 'json_content<<EOF' >> $GITHUB_OUTPUT
          cat ./config/1.0.json >> $GITHUB_OUTPUT
          echo 'EOF' >> $GITHUB_OUTPUT
    outputs:
      json_content: ${{ steps.get-json-content.outputs.json_content }} 
  build-plugins:
    runs-on: ubuntu-latest
    needs: load-config
    strategy:
        matrix:
          repo: ${{ fromJSON(needs.load-config.outputs.json_content) }}
    name: Build - ${{ matrix.repo.name }}
    steps:
      - name: Display matrix
        run: echo ${{ matrix }}
      - name: Trigger plugin build workflow
        uses: the-actions-org/workflow-dispatch@v4
        with:
          workflow: build.yml
          repo: ManiVaultStudio/${{ matrix.repo.name }}
          ref: ${{ matrix.repo.branch }}
          token: ${{ secrets.PA_TOKEN }}
          wait-for-completion: true
          wait-for-completion-timeout: 2h
          display-workflow-run-url: true
          workflow-logs: print
  build-installer:
    needs: build-plugins
    runs-on: ubuntu-latest
    steps:
      - name: Echo
        run: echo Building installer
        if: ${{ inputs.build-installer == 'false' }}

#name: Build core

#on:
#  workflow_dispatch
    
#jobs:
##  build-core:
    #name: Build core
    #runs-on: windows-latest
    #steps:
     # - name: Trigger workflow in core
     #   uses: peter-evans/repository-dispatch@v1
     #   with:
     #     token: ${{ secrets.PA_TOKEN }}
     ##     repository: ManiVaultStudio/core
      #    event-type: core-completed
      #    client-payload: |-
      #      {
      #        "repo": {
      #          "name": "ManiVaultStudio/core",
      #          "branch": "release/1.0"
      #        }
      #      }
