name: Initial Workflow

on:
  workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        repo: [[ 'BinIO', 'feature/core_1.0/0.5' ]]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Project A
        run: echo "Building Project A"

      - name: Trigger Repository B Workflow
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          repository: ManiVaultStudio/${{ matrix.repo[0] }}
          event-type: repository-a-completed
          client-payload: '{"ref": ${{ matrix.repo[1] }}'
