name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Application name'
        required: true
        default: '1.0'
        type: choice
        options:
        - '1.0'
        - genesurfer
        - test
        - comparison_viewer
      build-core:
        type: boolean
        default: true
        description: Build core
      build-data-plugins:
        type: boolean
        default: true
        description: Build data plugins
      build-plugins:
        type: boolean
        default: true
        description: Build plugins
      build-installer:
        type: boolean
        description: Build installer
        default: true
jobs:
  build-core:
    name: Build core
    runs-on: ubuntu-latest
    steps:
      - name: Trigger core build workflow
        uses: the-actions-org/workflow-dispatch@v4
        if: ${{ inputs.build-core == true }}
        with:
          workflow: build.yml
          repo: ManiVaultStudio/core
          ref: release/${{ inputs.version }}
          token: ${{ secrets.PA_TOKEN }}
          wait-for-completion: true
          wait-for-completion-timeout: 2h
          display-workflow-run-url: true
          workflow-logs: print
  load-config:
    name: Load configuration
    runs-on: ubuntu-latest
    needs: build-core
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Get JSON content
        id: get-json-content
        run: |
          echo 'json_content<<EOF' >> $GITHUB_OUTPUT
          cat ./config/${{ inputs.version }}.json >> $GITHUB_OUTPUT
          echo 'EOF' >> $GITHUB_OUTPUT
    outputs:
      json_content: ${{ steps.get-json-content.outputs.json_content }} 
  build-plugins:
    runs-on: ubuntu-latest
    needs: load-config
    strategy:
        matrix:
          repo: ${{ fromJSON(needs.load-config.outputs.json_content)['Plugins'] }}
    name: Build - ${{ matrix.repo.name }}
    steps:
      - name: Trigger plugin build workflow
        uses: the-actions-org/workflow-dispatch@v4
        if: ${{ inputs.build-plugins == true }}
        with:
          workflow: build.yml
          repo: ManiVaultStudio/${{ matrix.repo.name }}
          ref: ${{ matrix.repo.branch }}
          token: ${{ secrets.PA_TOKEN }}
          wait-for-completion: true
          wait-for-completion-timeout: 2h
          display-workflow-run-url: true
          workflow-logs: print
  build-installer:
    needs: build-plugins
    runs-on: ubuntu-latest
    steps:
      - name: Trigger installer build
        uses: the-actions-org/workflow-dispatch@v4
        if: ${{ inputs.build-installer == true }}
        with:
          workflow: manual.yml
          repo: ManiVaultStudio/Installer
          ref: main
          token: ${{ secrets.PA_TOKEN }}
          wait-for-completion: true
          wait-for-completion-timeout: 2h
          display-workflow-run-url: true
          workflow-logs: print
          inputs: '{ "version": "${{ inputs.version }}" }'
