name: Build release repos

on:
  workflow_dispatch
    
jobs:
  build-core:
    name: Build core
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Trigger workflow in core
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.PA_TOKEN }}
          repository: ManiVaultStudio/core
          event-type: core-completed
          client-payload: '{"ref": "release/1.0"}'
          
  build-plugins:
    name: Build plugins
    runs-on: windows-latest
    needs: build-core
    strategy:
      matrix:
        repo: [ { 'ImageLoaderPlugin', '1.0', 'ImageViewerPlugin', 'ManiVaultStudio/ScatterPlotPlugin']
    steps:
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.PA_TOKEN }}
          repository: ManiVaultStudio/${{ matrix.repo }}
          event-type: my-event
          client-payload: '{"ref": "release/core_1.0"}'

      
