name: Build release repos

on:
  workflow_dispatch
    
jobs:
  build-core:
    name: Build core
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

  build-plugins:
    name: Build plugins
    runs-on: windows-latest
    needs: build-core
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
