name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Application name'
        required: true
        default: 'comparison_viewer'
        type: choice
        options:
        - '1.0'
        - genesurfer
        - test
        - comparison_viewer
      build-core:
        type: boolean
        default: false
        description: Build core
      build-data-plugins:
        type: boolean
        default: false
        description: Build data plugins
      build-plugins:
        type: boolean
        default: false
        description: Build plugins
      build-installer:
        type: boolean
        description: Build installer
        default: true
jobs:
  build-core:
    name: Build core
    runs-on: ubuntu-latest
    steps:
      - name: Trigger core build workflow
        uses: the-actions-org/workflow-dispatch@v4
        if: ${{ inputs.build-core == true }}
        with:
          workflow: build.yml
          repo: ManiVaultStudio/core
          ref: release/${{ inputs.version }}
          token: ${{ secrets.PA_TOKEN }}
          wait-for-completion: true
          wait-for-completion-timeout: 2h
          display-workflow-run-url: true
          workflow-logs: print
  load-data-plugins-config:
    name: Load data plugins config
    runs-on: ubuntu-latest
    needs: build-core
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Get JSON content
        id: get-json-content
        run: |
          echo 'json_content<<EOF' >> $GITHUB_OUTPUT
          cat ./config/${{ inputs.version }}.json >> $GITHUB_OUTPUT
          echo 'EOF' >> $GITHUB_OUTPUT
    outputs:
      json_content: ${{ steps.get-json-content.outputs.json_content }}
  build-data-plugins:
    runs-on: ubuntu-latest
    needs: load-data-plugins-config
    strategy:
        matrix:
          repo: ${{ fromJSON(needs.load-data-plugins-config.outputs.json_content)['data_plugins'] }}
    name: Build - ${{ matrix.repo.name }}
    steps:
      - name: Trigger plugin build workflow
        uses: the-actions-org/workflow-dispatch@v4
        if: ${{ inputs.build-data-plugins == true }}
        with:
          workflow: build.yml
          repo: ManiVaultStudio/${{ matrix.repo.name }}
          ref: ${{ matrix.repo.branch }}
          token: ${{ secrets.PA_TOKEN }}
          wait-for-completion: true
          wait-for-completion-timeout: 2h
          display-workflow-run-url: true
          workflow-logs: print
          inputs: '{ "forceMacBuild": true }'
  load-plugins-config:
    name: Load plugins config
    runs-on: ubuntu-latest
    needs: build-data-plugins
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Get JSON content
        id: get-json-content
        run: |
          echo 'json_content<<EOF' >> $GITHUB_OUTPUT
          cat ./config/${{ inputs.version }}.json >> $GITHUB_OUTPUT
          echo 'EOF' >> $GITHUB_OUTPUT
    outputs:
      json_content: ${{ steps.get-json-content.outputs.json_content }}
  build-plugins:
    runs-on: ubuntu-latest
    needs: load-plugins-config
    strategy:
        matrix:
          repo: ${{ fromJSON(needs.load-plugins-config.outputs.json_content)['plugins'] }}
    name: Build - ${{ matrix.repo.name }}
    steps:
      - name: Trigger plugin build workflow
        uses: the-actions-org/workflow-dispatch@v4
        if: ${{ inputs.build-plugins == true }}
        with:
          workflow: build.yml
          repo: ManiVaultStudio/${{ matrix.repo.name }}
          ref: ${{ matrix.repo.branch }}
          token: ${{ secrets.PA_TOKEN }}
          wait-for-completion: true
          wait-for-completion-timeout: 2h
          display-workflow-run-url: true
          workflow-logs: print
  load-installer-config-a:
    name: Load installer config (1)
    runs-on: ubuntu-latest
    needs: build-plugins
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Get JSON content
        id: get-json-content
        run: |
          echo 'json_content<<EOF' >> $GITHUB_OUTPUT
          cat ./config/${{ inputs.version }}.json >> $GITHUB_OUTPUT
          echo 'EOF' >> $GITHUB_OUTPUT
    outputs:
      json_content: ${{ steps.get-json-content.outputs.json_content }}
  load-installer-config-b:
    name: Load installer config (2)
    runs-on: ubuntu-latest
    needs: load-installer-config-a
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Load JSON and extract part of it
        id: extract_json
        run: |
          # Load JSON from file
          json_content=$(cat ./config/${{ inputs.version }}.json)

          # Extract part of the JSON using jq
          extracted_json=$(echo "$json_content" | jq '.installer_config')

          # Convert extracted JSON to a string and save it to an output
          echo "extracted_json_str=$(echo "$extracted_json" | jq -c .)" >> $GITHUB_ENV

      - name: Use extracted JSON string
        run: |
          echo "The extracted JSON string is: $extracted_json_str"
      - name: Trigger installer build
        uses: the-actions-org/workflow-dispatch@v4
        if: ${{ inputs.build-installer == true }}
        with:
          workflow: manual.yml
          repo: ManiVaultStudio/Installer
          ref: main
          token: ${{ secrets.PA_TOKEN }}
          wait-for-completion: true
          wait-for-completion-timeout: 2h
          display-workflow-run-url: true
          workflow-logs: print
          inputs: '{"os":"Macos","version":"comparison_viewer","application_name":"Cytosplore"}'
    
