name: Test releaser

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Application name'
        required: true
        default: 'test'
        type: choice
        options:
        - '1.1'
        - '1.0'
        - genesurfer
        - test
        - comparison_viewer
      build-core:
        type: boolean
        default: false
        description: Build core
      build-data-plugins:
        type: boolean
        default: false
        description: Build data plugins
      build-plugins:
        type: boolean
        default: true
        description: Build plugins
      build-installer:
        type: boolean
        description: Build installer
        default: false
jobs:
  build-core:
    name: Build core
    runs-on: ubuntu-latest
    steps:
      - name: Trigger core build workflow
        uses: the-actions-org/workflow-dispatch@v4
        if: ${{ inputs.build-core == true }}
        with:
          workflow: build.yml
          repo: ManiVaultStudio/core
          ref: release/${{ inputs.version }}
          token: ${{ secrets.PA_TOKEN }}
          wait-for-completion: true
          wait-for-completion-timeout: 2h
          display-workflow-run-url: true
          workflow-logs: print
  load-data-plugins-config:
    name: Load data plugins config
    runs-on: ubuntu-latest
    needs: build-core
    continue-on-error: true
    outputs:
      matrix: ${{ steps.extract-matrix.outputs.matrix }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Load plugins matrix from JSON
        id: extract-plugins-matrix
        run: |
          plugins=$(jq -c '.plugins' config/test.json)
          echo "plugins=$plugins" >> $GITHUB_OUTPUT
      - name: Debug plugins JSON content
        id: debug-plugins-json-content
        run: echo $plugins
    
